apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  labels:
    app: nextjs-app
spec:
  selector:
    app: nextjs-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer
